package modelo;
// Generated May 23, 2016 6:22:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nomina generated by hbm2java
 */
@Entity
@Table(name = "Nomina", catalog = "Final")
public class Nomina implements java.io.Serializable {

	private String cedula;
	private String empleado;
	private float salarioMensual;
	private float diasTrabajados;
	private Float basico;
	private Float auxilioTransporte;
	private Float totalDevengado;
	private Float eps;
	private Float pension;
	private Float netoPagado;
	private Float totalDeducido;

	public Nomina() {
	}

	public Nomina(String cedula, String empleado, float salarioMensual, float diasTrabajados) {
		this.cedula = cedula;
		this.empleado = empleado;
		this.salarioMensual = salarioMensual;
		this.diasTrabajados = diasTrabajados;
	}

	public Nomina(String cedula, String empleado, float salarioMensual, float diasTrabajados, Float basico,
			Float auxilioTransporte, Float totalDevengado, Float eps, Float pension, Float netoPagado,
			Float totalDeducido) {
		this.cedula = cedula;
		this.empleado = empleado;
		this.salarioMensual = salarioMensual;
		this.diasTrabajados = diasTrabajados;
		this.basico = basico;
		this.auxilioTransporte = auxilioTransporte;
		this.totalDevengado = totalDevengado;
		this.eps = eps;
		this.pension = pension;
		this.netoPagado = netoPagado;
		this.totalDeducido = totalDeducido;
	}

	@Id

	@Column(name = "Cedula", unique = true, nullable = false, length = 20)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "Empleado", nullable = false, length = 20)
	public String getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(String empleado) {
		this.empleado = empleado;
	}

	@Column(name = "SalarioMensual", nullable = false, precision = 12, scale = 0)
	public float getSalarioMensual() {
		return this.salarioMensual;
	}

	public void setSalarioMensual(float salarioMensual) {
		this.salarioMensual = salarioMensual;
	}

	@Column(name = "DiasTrabajados", nullable = false, precision = 12, scale = 0)
	public float getDiasTrabajados() {
		return this.diasTrabajados;
	}

	public void setDiasTrabajados(float diasTrabajados) {
		this.diasTrabajados = diasTrabajados;
	}

	@Column(name = "Basico", precision = 12, scale = 0)
	public Float getBasico() {
		return this.basico;
	}

	public void setBasico(Float basico) {
		this.basico = basico;
	}

	@Column(name = "AuxilioTransporte", precision = 12, scale = 0)
	public Float getAuxilioTransporte() {
		return this.auxilioTransporte;
	}

	public void setAuxilioTransporte(Float auxilioTransporte) {
		this.auxilioTransporte = auxilioTransporte;
	}

	@Column(name = "TotalDevengado", precision = 12, scale = 0)
	public Float getTotalDevengado() {
		return this.totalDevengado;
	}

	public void setTotalDevengado(Float totalDevengado) {
		this.totalDevengado = totalDevengado;
	}

	@Column(name = "Eps", precision = 12, scale = 0)
	public Float getEps() {
		return this.eps;
	}

	public void setEps(Float eps) {
		this.eps = eps;
	}

	@Column(name = "Pension", precision = 12, scale = 0)
	public Float getPension() {
		return this.pension;
	}

	public void setPension(Float pension) {
		this.pension = pension;
	}

	@Column(name = "NetoPagado", precision = 12, scale = 0)
	public Float getNetoPagado() {
		return this.netoPagado;
	}

	public void setNetoPagado(Float netoPagado) {
		this.netoPagado = netoPagado;
	}

	@Column(name = "TotalDeducido", precision = 12, scale = 0)
	public Float getTotalDeducido() {
		return this.totalDeducido;
	}

	public void setTotalDeducido(Float totalDeducido) {
		this.totalDeducido = totalDeducido;
	}

}
